# 一些配置教程
# https://squidfunk.github.io/mkdocs-material
# https://www.mkdocs.org
# https://zhuanlan.zhihu.com/p/383582472
# https://markdown-docs-zh.readthedocs.io/zh-cn/latest
# https://docs.netlify.com/frameworks/#mkdocs
# https://www.starfallprojects.co.uk/projects/deploy-host-docs/deploy-mkdocs-material-vercel/

site_name: SANP DOCS

theme:
  name: material
  language: zh
  features:
    # - navigation.instant # 即时加载, 在 Firefox 下有内存泄露的问题
    - navigation.instant.prefetch # 即时预加载
    - navigation.instant.progress # 加载进度显示
    - navigation.instant.preview # 即时预览
    - navigation.tracking # 锚点跟踪
    - navigation.tabs # 导航选项卡
    - navigation.tabs.sticky # 始终显示导航选项卡
    - navigation.path # 显示导航路径
    # - navigation.prune # 导航修剪
    # - navigation.indexes # 章节索引页
    - navigation.expand # 侧边栏展开
    - navigation.footer # 启用页脚
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索共享
    - content.action.edit # 编辑本页按钮
    # - content.action.view # 查看本页源代码
    - content.code.copy # 代码块复制按钮
    - content.code.annotate # 代码注解
    - content.tabs.link # 链接的内容选项卡
    - content.tooltips # 改进的工具提示

  palette: # 颜色

    # 自动模式的配色切换
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 跟随系统配色

    # 浅色模式的配色切换
    - media: "(prefers-color-scheme: light)"
      scheme: default # 配色
      primary: white # 原色
      accent: light blue # 强调色
      toggle:
        icon: material/brightness-7
        name: 浅色主题

    # 深色模式的配色切换
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 黑暗主题

  logo: assets/site_resources/logo.png
  favicon: assets/site_resources/favicon.png

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search # 搜索功能
  - tags # 标签插件
  - glightbox # 图像缩放

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zhulinyv
      name: Github
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/313511663
      name: 哔哩哔哩
    - icon: fontawesome/solid/blog
      link: https://zhulinyv.github.io
      name: 可爱的小丫头片子酱的肥宅快乐水妹汁加工厂股份无限公司
    - icon: fontawesome/solid/envelope
      link: mailto:zhulinyv2005@outlook.com
      name: 联系邮箱

  generator: true # 生成器通知

copyright: Copyright &copy; 2024 zhulinyv

repo_url: https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv
repo_name: Semi-Auto-NovelAI-to-Pixiv
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.striphtml
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - admonition
  - toc:
      permalink: ☍
      permalink_title: 锚链接到此处
      title: 目录
  - tables

nav:
- "主页": index.md
- "项目部署与更新":
  - "前言": deploy/index.md
  - "1. 整合包":
    - "1. 通过 release 下载": deploy/modpack/release/index.md
    - "2. 通过群文件下载": deploy/modpack/groupfile/index.md
    - "解压安装": deploy/modpack/extract/index.md
  - "2. 手动部署": deploy/byhand/index.md
- "各功能使用方法":
  - "前言": guide/index.md
  - "文生图":
    - "文生图": guide/t2i/text2image/index.md
    - "随机蓝图": guide/t2i/text2image_nsfw/index.md
    - "随机图片": guide/t2i/text2image_sfw/index.md
    - "Vibe": guide/t2i/vibe_transfer/index.md
    - "CasRand": guide/t2i/casrand/index.md
    - "画风生成": guide/t2i/random_artists/index.md
    - "推文生图工具": guide/t2i/stories2image/index.md
  - "图生图":
    - "图生图": guide/i2i/image2image/index.md
    - "视频转绘": guide/i2i/movie2movie/index.md
    - "分块重绘": guide/i2i/tiled_upscale/index.md
    - "Enhance": guide/i2i/enhance/index.md
  - "局部重绘":
    - "局部重绘": guide/inp/inpaint/index.md
    - "涂鸦重绘": guide/inp/draw_inpaint/index.md
  - "导演工具":
    - "移除背景": guide/dir/remove_bg/index.md
    - "线条画": guide/dir/lineart/index.md
    - "素描": guide/dir/skecth/index.md
    - "上色": guide/dir/colorize/index.md
    - "表情": guide/dir/emotion/index.md
    - "整理": guide/dir/declutter/index.md
  - "超分降噪": guide/waifu2x.md
  - "自动打码": guide/mosaic.md
  - "添加水印": guide/watermark.md
  - "上传Pixiv": guide/pixiv.md
  - "图片筛选": guide/selector.md
  - "抹除数据": guide/remove.md
  - "法术解析": guide/magic.md
  - "GPT": guide/gpt4free.md
  - "压缩整理": guide/compression.md
  - "插件商店": guide/plugin.md
  - "配置设置": guide/setting.md
  - "其它": guide/else.md
- "可能出现的问题": help.md
- "鸣谢列表及待办": appendix.md
- "关于": about.md
